pipeline {
    agent { label 'master' }
    //{ label 'master'}

        stages {
            
            stage ('install') {
                steps {
                  dir("build_node"){
                        sh "npm install"
                  }
                   
                   
                }
            }
            
            stage ('test') {
                steps {
                  dir("build_java"){
                        echo "mvn clean compile test"
                  }
                   
                   
                }
            }

            stage ('Create docker image') {
                steps {
                    dir("build_java"){

                        echo "mvn -f pom.xml clean install -Dmaven.test.skip=true"
                        echo "tree"
                    }   
                }
            }
  
           
        }
}
