pipeline {
    agent any
    stages {
        stage('Install') {
            steps {
                dir('build_node') {
                    sh 'npm install'
                }
            }
        }
        stage('Test') {
            steps {
                dir('build_node') {
                    sh 'npm test'
                }
            }
        }
        // Otros stages
    }
}
