pipeline {
    agent any

    tools {
        jenkins.plugins.nodejs.tools.NodeJSInstallation('20.11.0')
    }

    stages {
        stage('install') {
            steps {
                dir("build_node") {
                    sh "npm install"
                }
            }
        }
        stage('test') {
            steps {
                dir("build_node") {
                    sh "npm test"
                }
            }
        }
    }
}
