pipeline {
    agent any

    stages {
        stage('Stop and remove container') {
            steps {
                script {
                    // Comprobar si el contenedor está en ejecución
                    def containerId = sh(script: 'docker ps -q --filter name=proyecto-qalatest81', returnStdout: true).trim()
                    if (containerId) {
                        // Detener y eliminar el contenedor
                        sh "docker stop ${containerId}"
                        sh "docker rm ${containerId}"
                    } else {
                        echo "No container to stop/remove"
                    }
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    // Construir la imagen Docker
                    sh 'docker build -t iproyecto-qa:latest jobs/dockerweb/'
                }
            }
        }

        stage('Run') {
            steps {
                script {
                    // Ejecutar el contenedor Docker
                    sh 'docker run -d -p 81:80 --name proyecto-qalatest81 iproyecto-qa:latest'
                }
            }
        }

        stage('Cleanup') {
            steps {
                script {
                    // Detener y eliminar el contenedor
                    sh "docker stop proyecto-qalatest81 || true"
                    sh "docker rm proyecto-qalatest81 || true"
                }
            }
        }
    }
}
